name: release
on:
  push:
    tags:
      - 'v*'
      - '!v*-rc*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      RELEASE_ZIP_NAME: A32NX-stable.zip
      BUILD_DIR_NAME: stable
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build A32NX
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
          ./scripts/dev-env/run.sh ./scripts/build.sh --no-tty
      - name: Build ZIP file
        run: |
          ./scripts/dev-env/run.sh node ./scripts/fragment.js

          mkdir ./${{ env.BUILD_DIR_NAME }}
          zip -r ./${{ env.BUILD_DIR_NAME }}/${{ env.RELEASE_ZIP_NAME }} ./flybywire-aircraft-a320-neo/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.BUILD_DIR_NAME }}/${{ env.RELEASE_ZIP_NAME }}
          asset_name: ${{ env.RELEASE_ZIP_NAME }}
          asset_content_type: application/zip
      - name: Upload to Bunny CDN
        env:
          BUNNY_BUCKET_PASSWORD: ${{ secrets.BUNNY_BUCKET_PASSWORD }}
          BUNNY_SECRET_TOKEN: ${{ secrets.BUNNY_SECRET_TOKEN }}
          BUNNY_BUCKET_DESTINATION: addons/a32nx/stable
        run: ./scripts/cdn.sh $BUNNY_BUCKET_DESTINATION
      - name: Upload to DigitalOcean CDN
        uses: LibreTexts/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: ./${{ env.BUILD_DIR_NAME }}
          DEST_DIR: ${{ env.BUILD_DIR_NAME }}
          SPACE_NAME: ${{ secrets.CDN_SPACE_NAME }}
          SPACE_REGION: ${{ secrets.CDN_SPACE_REGION }}
          SPACE_ACCESS_KEY_ID: ${{ secrets.CDN_SPACE_ACCESS_KEY_ID }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.CDN_SPACE_SECRET_ACCESS_KEY }}
